
# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4


pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'
  PYTHON_LOCATION: 'undefined'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    addToPath: true
    architecture: 'x64'
  name: pyTools

- script: 'python -m pip install --upgrade pip setuptools wheel'
  displayName: 'Install tools'

- script: 'pip install -r Python_code\requirements.txt'
  displayName: 'Install requirements'
  
- bash: echo '##vso[task.setvariable variable=PYTHON_LOCATION]$(pyTools.pythonLocation)'
  displayName: 'Set new variable value'


- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'
    vsVersion: '15.0'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'